#配置切换
spring:
  profiles:
    active: dev
  rabbitmq:
    host: 192.168.244.129
    port: 5672
    username: admin
    password: admin

#端口和path
server:
  port: 8008
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /jhyang

# 分页插件配置
pagehelper:
  helper-dialect: oracle
  reasonable: false
  support-methods-arguments: true
  params: count

##日志
logging:
  config: classpath:logback-spring.xml

#接口文档输出
swagger:
  production: false
  basic:
    enable: true
    username: admin
    password: 123456

